Add error handling for unset CLI_VERSION in release workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -167,11 +167,13 @@ jobs:
           echo "CLI version being packed is $CLI_VERSION"
 
           # Export CLI version as an environment variable
+          if [ -z "$CLI_VERSION" ]; then
+          echo "Error: CLI_VERSION is not set or is empty."
+          exit 1
+          fi
+
           echo "CLI_VERSION=$CLI_VERSION" >> $GITHUB_ENV
-          echo "CLI_VERSION=${{ env.CLI_VERSION }}" >> $GITHUB_OUTPUT
-          
-          # Echo the CLI version for debugging purposes      
-      
+                
 
       # Create the release or prerelease
       - name: Create Release or Prerelease
